### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by higaru2** [BOBONA/Just-a-Sample#4]
hello Bobona!
fantastic sampler. very minimal yet functional concept.
bigups!

is there any chance that you can compile it
so it can work on old macs like mine!?
( High Sierra, 10.13.6 )

thanks!!!!

**Comment by BOBONA** [comment]
Thanks for reaching out! I've included builds with deployment target set to 10.13 in the releases section. I can't test them on my laptop though. 

If you enjoy using the plugin, feel free to star the repo on GitHub, leave feedback on [itch.io](https://binyaminf.itch.io/just-a-sample), and share with friends.

**Comment by higaru2** [comment]
thank you!
just tried the "legacy" builds you uploaded
and still no go :( they dont even show in Reaper on High Sierra
for some strange reason :(
thanks for trying anyways.

**Comment by BOBONA** [comment]
Just to make sure, you've put the VST3 file in "/Library/Audio/Plug-Ins/VST3/" and the AU file in "/Library/Audio/Plug-Ins/Components/"

Unfortunately, there's no proper way for me to test on an older system.

**Comment by higaru2** [comment]
I tried only the .au
and it doesnt show:(
( yep, I put it in the right place)

**Comment by BOBONA** [comment]
Ah. Sorry to hear that. If you don't use Logic, then it is worth trying VST3. I think even the newer VST3 ought to work fine? AU specifically are system-level.

**Comment by higaru2** [comment]
just tried the legacy vst3
and it is the same:
doesnt show in reaper:(

**Comment by BOBONA** [comment]
Sorry I couldn't help. You can always try building the plugin from source on your own, although I wouldn't recommend it if you haven't done xcode development before.

**Comment by higaru2** [comment]
thanks for trying:)
